version: "3.9" # версия docker-compose

services:
  web:
    image: piligrimdev/codelens-web
    hostname: codelens
    env_file:
      - .env
    environment:
      - TESSERACT_EXE_PATH=/usr/bin/tesseract
      - CSRF_TRUSTED_ORIGINS=http://localhost:1337
      - DEBUG=0
      - TEST=1
      - PYTHONUBUFFERED=1
    command: > 
      sh -c "python manage.py migrate &&
             gunicorn codelens_backend.wsgi:application --bind 0.0.0.0:8080"
    expose:
      - 8080
    restart: always
    volumes:
      - codelens_static_volume:/home/app/web/static

  nginx:
    image: piligrimdev/codelens-nginx
    volumes:
      - codelens_static_volume:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - web

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=600

volumes:
  codelens_static_volume:
